### ISSUE TITLE
Taskcat container missing go lang runtimes?

### ISSUE THREAD

**Issue by DarwinJS** [aws-ia/taskcat#747]
**Describe the bug**
I get errors trying to use taskcat that seems to indicate that it is missing the go lang runtimes (or they are not mapped when I enter the container with `sh`):

 Initial Error:
 
 This command `docker run -it -v $(pwd):/mnt -v ${HOME}/.aws/credentials:/root/.aws/credentials:ro -v /var/run/docker.sock:/var/run/docker.sock taskcat/taskcat taskcat --debug test run --no-delete --keep-failed --test-names smallest-possible --regions eu-central-1` 
 
 Eventually results in this error:
 
```
[INFO   ] : Packaging lambda source from /mnt/submodules/quickstart-amazon-eks/functions/source/HelmReleaseResource using docker image taskcat-build-9bcb5b76772059b7bbae56916a00c99a
[WARN   ] : No stacks were created... skipping cleanup.
[ERROR  ] : BuildError The command '/bin/sh -c GOPROXY=direct go mod download' returned a non-zero code: 1
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/taskcat/_cli.py", line 46, in main
    [cli.run](http://cli.run/)()
  File "/usr/local/lib/python3.8/site-packages/taskcat/_cli_core.py", line 314, in run
    return getattr(command(), subcommand)(**args)
  File "/usr/local/lib/python3.8/site-packages/taskcat/_cli_modules/test.py", line 167, in run
    with test:
  File "/usr/local/lib/python3.8/site-packages/taskcat/testing/base_test.py", line 58, in __enter__
    raise ex
  File "/usr/local/lib/python3.8/site-packages/taskcat/testing/base_test.py", line 55, in __enter__
    [self.run](http://self.run/)()
  File "/usr/local/lib/python3.8/site-packages/taskcat/testing/_cfn_test.py", line 102, in run
    LambdaBuild(self.config, self.config.project_root)
  File "/usr/local/lib/python3.8/site-packages/taskcat/_lambda_build.py", line 34, in __init__
    self._build_submodules()
  File "/usr/local/lib/python3.8/site-packages/taskcat/_lambda_build.py", line 41, in _build_submodules
    self._recurse(self._project_root, rel_source, rel_zip)
  File "/usr/local/lib/python3.8/site-packages/taskcat/_lambda_build.py", line 52, in _recurse
    self._build_lambdas(source_path, output_path)
  File "/usr/local/lib/python3.8/site-packages/taskcat/_lambda_build.py", line 67, in _build_lambdas
    self._docker_build(path, tag)
  File "/usr/local/lib/python3.8/site-packages/taskcat/_lambda_build.py", line 135, in _docker_build
    _, logs = self._docker.images.build(path=str(path), tag=tag)
  File "/usr/local/lib/python3.8/site-packages/docker/models/images.py", line 287, in build
    raise BuildError(chunk['error'], result_stream)
docker.errors.BuildError: The command '/bin/sh -c GOPROXY=direct go mod download' returned a non-zero code: 1
```

Loading container and trying to run go commands from above:
```
$ docker run -it -v $(pwd):/mnt -v ${HOME}/.aws/credentials:/root/.aws/credentials:ro -v /var/run/docker.sock:/var/run/docker.sock taskcat/taskcat sh
/mnt # /bin/sh -c GOPROXY=direct go mod download
/mnt # GOPROXY=direct go mod download
sh: go: not found
```

**To Reproduce**
1. Are you testing a *QuickStart* or *Custom template*?
2. Attach or link a copy of the template if possible (**remove any sensitive info**)
3. Provide the parameters that you passed. (**remove any sensitive info**)
4. How did you install taskcat? (docker or pip3)
5. Are you using a *profile*, *an instance role* or  *access keys* to run taskcat?
6. Is your AWS environment configured via `aws configure`?

**Expected behavior**

**Screenshots**

**Version (Please make sure you are running the latest version of taskcat)
 - Taskcat Container AND Binary Version: 0.9.30

 Note: Python Version (python3 required)

To find versions:
*Via taskcat*: `taskcat -V`
*Via pip3*: `pip3 show taskcat`

Note: both version should match **=> Yes they match**

**Additional context**

**Comment by troy-ameigh** [comment]
I am looking into this

**Comment by DarwinJS** [comment]
@troy-ameigh - I just added the version details to the description - it is 0.9.30

**Comment by DarwinJS** [comment]
@troy-ameigh - I just tested the 0.9.31 container you pushed and I get the same error.

**Comment by DarwinJS** [comment]
My code is here if it helps: https://github.com/aws-quickstart/quickstart-eks-gitlab/pull/128
